# C Compiler we are using
CC = gcc

# Adding compiler flags
CFLAGS = -g -wall

# the build target:
TARGET = $(EXE)

all: $(TARGET)

$(TARGET): $(TARGET).c ; $(CC) $(CFLAGS) -o $(TARGET) $(TARGET).c $(LFLAGS)